# 🐳 Visión Maestra Platform - Enterprise Container
# Auto-generated by ADW Deploy Solution for production deployment
# Multi-stage build optimized for TypeScript/Node.js enterprise platform

# Build Stage - Development Environment
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /usr/src/app

# Install build dependencies
RUN apk add --no-cache \
    git \
    python3 \
    make \
    g++ \
    && npm install -g npm@latest

# Copy package files for dependency installation
COPY package*.json ./
COPY tsconfig*.json ./

# Install dependencies (including devDependencies for build)
RUN npm ci --include=dev

# Copy source code
COPY . .

# Build the application
RUN npm run build

# Remove development dependencies
RUN npm ci --omit=dev && npm cache clean --force

# Production Stage - Optimized Runtime
FROM node:20-alpine AS production

# Set Node environment
ENV NODE_ENV=production
ENV NODE_OPTIONS="--max-old-space-size=4096"

# Create non-root user for security
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nextjs -u 1001

# Set working directory
WORKDIR /usr/src/app

# Install runtime dependencies
RUN apk add --no-cache \
    dumb-init \
    curl \
    tini \
    && rm -rf /var/cache/apk/*

# Copy built application from builder stage
COPY --from=builder --chown=nextjs:nodejs /usr/src/app/dist ./dist
COPY --from=builder --chown=nextjs:nodejs /usr/src/app/node_modules ./node_modules
COPY --from=builder --chown=nextjs:nodejs /usr/src/app/package*.json ./

# Copy configuration files
COPY --chown=nextjs:nodejs config/ ./config/
COPY --chown=nextjs:nodejs scripts/ ./scripts/

# Create necessary directories
RUN mkdir -p /usr/src/app/logs && \
    chown -R nextjs:nodejs /usr/src/app

# Expose application port
EXPOSE 3000

# Health check endpoint
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD curl -f http://localhost:3000/health || exit 1

# Switch to non-root user
USER nextjs

# Use tini for proper signal handling
ENTRYPOINT ["/sbin/tini", "--"]

# Start the application
CMD ["node", "dist/src/platform/VisualMaestraMain.js"]

# 🚀 Container Metadata
LABEL org.opencontainers.image.title="Visión Maestra Platform" \
      org.opencontainers.image.description="6-Component Enterprise Autonomous Development Platform" \
      org.opencontainers.image.vendor="ADW Deploy Solution" \
      org.opencontainers.image.version="1.0.0" \
      org.opencontainers.image.created="2026-03-08" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.documentation="https://github.com/JLMA-Agentic-Ai/contexto"

# Security and performance optimizations applied:
# ✅ Non-root user (nextjs:1001)
# ✅ Multi-stage build for minimal image size
# ✅ Health check endpoint configured
# ✅ Proper signal handling with tini
# ✅ Security scannable with Trivy/Grype
# ✅ Production-optimized Node.js settings